import { useState } from 'react';
import { Icon, money } from './ui.jsx';
import {SettlementActions} from './PaymentTools.jsx';
export default function Balances({data,userId,name,reload=async()=>{}}){
 const [everyone,setEveryone]=useState(false),[ledger,setLedger]=useState(data.trip.status==='ended'&&data.kittySettlement?'kitty':'personal');
 const transactions=ledger==='kitty'?(data.kittySettlement?.transactions||[]):data.transactions;
 const netFor=id=>transactions.reduce((sum,t)=>sum+(t.to===id?t.amountPaise:0)-(t.from===id?t.amountPaise:0),0);
 const explanation=t=><details className="settlement-reason"><summary>Why this payment?</summary><p>{name(t.from)} owes {money(-netFor(t.from))} overall, and {name(t.to)} is owed {money(netFor(t.to))} overall after personal payments and expense shares are offset. Paying {money(t.amountPaise)} directly settles that amount of both balances without passing it through other members. Each person's final balance stays the same.</p></details>;
 const owed=transactions.filter(t=>t.to===userId).reduce((s,t)=>s+t.amountPaise,0);
 const owing=transactions.filter(t=>t.from===userId).reduce((s,t)=>s+t.amountPaise,0);
 return <>{!data.kittySettlement&&<p className="ledger-note">Reconnect to load Kitty settlement for this saved trip.</p>}<div className="settlement-tabs" role="group" aria-label="Settlement ledger"><button aria-pressed={ledger==='personal'} onClick={()=>setLedger('personal')}>Personal Pocket</button><button disabled={!data.kittySettlement} aria-pressed={ledger==='kitty'} onClick={()=>setLedger('kitty')}>Group Kitty</button></div><p className="page-description">{ledger==='kitty'?(data.kittySettlement?.leadId===userId?'As group lead, collect amounts owed and return unused contributions.':'Your contributions minus your share of spending. Settle with '+name(data.kittySettlement?.leadId)+'.'):'Direct payments after offsetting personal expenses.'}</p><div className="settlement-totals"><div><span>You are owed</span><strong className="positive">{money(owed)}</strong></div><div><span>You owe</span><strong className="negative">{money(owing)}</strong></div></div><SettlementActions data={data} userId={userId} name={name} ledger={ledger} reload={reload}/><p className="ledger-note"><Icon name="lock" size={16}/>{ledger==='kitty'?(data.kittySettlement?.leadId===userId?'Refund members in credit. Collect from members who owe.':'Positive credit: the lead refunds you. Negative credit: you pay the lead.'):'Chained debts are offset: if A owes B ₹100 and B owes C ₹100, A pays C ₹100. B has a zero net balance. Kitty settlement stays separate.'}</p><button className="text-button" aria-expanded={everyone} onClick={()=>setEveryone(!everyone)}>Whole-trip balances<Icon name="down"/></button>{everyone&&<section className="settlement-list">{transactions.length?transactions.map(t=><div key={t.from+t.to}><div className="whole-trip-balance"><span>{name(t.from)} owes {name(t.to)}</span><strong>{money(t.amountPaise)}</strong></div>{ledger==='personal'&&explanation(t)}</div>):<p className="ledger-note">Everyone is settled up.</p>}</section>}</>;
}
