import {useEffect,useRef,useState} from 'react';
import {api} from '../api.js';
import {money,Icon} from './ui.jsx';
import './payments.css';

export function PaymentProfile(){
 const [upi,setUpi]=useState(''),[loaded,setLoaded]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const p=await api('/payments/profile');setUpi(p.upiId);setLoaded(true);}catch(e){setMessage(e.message);}}
 async function save(e){e.preventDefault();setBusy(true);try{await api('/payments/profile',{upiId:upi});setMessage('UPI ID saved. This checks the format, not bank ownership.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <details className="payment-settings" onToggle={e=>{if(e.currentTarget.open&&!loaded)void load();}}><summary>My UPI ID</summary><p>Add an optional receiving address. Only trip members who owe you can retrieve it. We never ask for your UPI PIN or OTP.</p><form onSubmit={save}><label>UPI ID<input value={upi} onChange={e=>setUpi(e.target.value)} placeholder="yourname@bank" autoComplete="off" autoCapitalize="none" spellCheck="false" maxLength={100}/></label><small>Clear the field and save to remove your UPI ID.</small><button className="primary" disabled={!loaded||busy}>{busy?'Saving…':'Save UPI ID'}</button></form>{message&&<p role="status">{message}</p>}</details>;
}
export function SettlementActions({data,userId,name,ledger,reload}){
 const [payment,setPayment]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState(null);
 const transactions=ledger==='personal'?data.transactions:data.kittySettlement?.transactions||[];
 const records=(data.payments||[]).filter(p=>p.ledger===ledger);
 async function act(path,body){setBusy(true);setMessage('');try{await api('/payments/trips/'+data.trip._id+path,body);await reload();return true;}catch(e){setMessage(e.message);return false;}finally{setBusy(false);}}
 return <section className="settlement-actions" aria-label="Payments and approvals"><h2>Pay & settle</h2><p>Balances change only after the recipient confirms receipt.</p>
 {transactions.filter(t=>t.from===userId||t.to===userId).map(t=>{const pending=records.some(p=>p.state==='pending'&&p.from===t.from&&p.to===t.to);return <article className="payment-action" key={t.from+t.to}><div><strong>{t.from===userId?'Pay '+name(t.to):name(t.from)+' owes you'}</strong><span>{money(t.amountPaise)}</span></div>{t.from===userId?<button className="primary" disabled={pending||busy} onClick={()=>setPayment(t)}>{pending?'Approval pending':'Pay / record payment'}</button>:<button className="secondary" disabled={pending||busy} onClick={async()=>{if(await act('/remind',{to:t.from,ledger}))setMessage('Reminder sent to their inbox. Phone alerts depend on their notification settings.');}}>{pending?'Review payment below':'Remind'}</button>}</article>;})}
 {!transactions.some(t=>t.from===userId||t.to===userId)&&<p>You have no outstanding payments in this ledger.</p>}
 {records.filter(p=>p.state==='pending').map(p=><article className="payment-request" key={p._id}><strong>{p.from===userId?'You reported paying '+name(p.to):name(p.from)+' reported paying you'} · {money(p.amountPaise)}</strong><p>Waiting for recipient confirmation</p>{p.to===userId?<div className="payment-buttons"><button className="primary" disabled={busy} onClick={()=>setReview(p)}>Review receipt</button><button className="secondary" disabled={busy} onClick={()=>act('/requests/'+p._id+'/reject',{})}>Not received</button></div>:<button className="text-button" disabled={busy} onClick={()=>act('/requests/'+p._id+'/cancel',{})}>Cancel request</button>}</article>)}
 {records.some(p=>p.state!=='pending')&&<details><summary>Payment history</summary>{records.filter(p=>p.state!=='pending').sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).map(p=><p key={p._id}>{name(p.from)} → {name(p.to)} · {money(p.amountPaise)}<br/><small>{p.state==='accepted'?'Receipt confirmed':p.state} · {new Date(p.resolvedAt||p.createdAt).toLocaleDateString()}</small></p>)}</details>}
 {message&&<p role="status" className="payment-message">{message}</p>}
 {payment&&<PaymentDialog transaction={payment} data={data} ledger={ledger} name={name} onClose={()=>setPayment(null)} onDone={async()=>{setPayment(null);await reload();}}/>}
 {review&&<ConfirmReceipt message={message} payment={review} name={name} busy={busy} onClose={()=>setReview(null)} onConfirm={async()=>{if(await act('/requests/'+review._id+'/accept',{}))setReview(null);}}/>}
 </section>;
}
function useDialog(ref){useEffect(()=>{const previous=document.activeElement,overflow=document.body.style.overflow;const el=ref.current;document.body.style.overflow='hidden';el.showModal();return()=>{el.close();document.body.style.overflow=overflow;previous?.focus();};},[]);}
function ConfirmReceipt({message,payment,name,busy,onClose,onConfirm}){const dialog=useRef(null);useDialog(dialog);return <dialog className="payment-dialog" ref={dialog} aria-labelledby="receipt-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><h2 id="receipt-title">Have you received {money(payment.amountPaise)}?</h2><p>Check your bank or UPI app for the payment from {name(payment.from)}. Confirming updates the trip balance. TripRoam cannot verify the bank transaction.</p>{message&&<p role="alert" className="error">{message}</p>}<div className="payment-buttons"><button className="secondary" disabled={busy} onClick={onClose}>Go back</button><button className="primary" disabled={busy} onClick={onConfirm}>Yes, received</button></div></dialog>;}
function PaymentDialog({transaction,data,ledger,name,onClose,onDone}){
 const dialog=useRef(null);useDialog(dialog);
 const [recipient,setRecipient]=useState(null),[amount,setAmount]=useState((transaction.amountPaise/100).toFixed(2)),[error,setError]=useState(''),[busy,setBusy]=useState(false),[checked,setChecked]=useState(false);
 const clientId=useRef(crypto.randomUUID()),submitted=useRef(null);
 useEffect(()=>{let active=true;api('/payments/trips/'+data.trip._id+'/recipient/'+transaction.to).then(p=>{if(active)setRecipient(p);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 const amountPaise=Math.round(Number(amount)*100),valid=/^\d+(\.\d{1,2})?$/.test(amount)&&Number.isSafeInteger(amountPaise)&&amountPaise>0&&amountPaise<=transaction.amountPaise;
 const query=new URLSearchParams({pa:recipient?.upiId||'',pn:recipient?.displayName||name(transaction.to),am:(amountPaise/100).toFixed(2),cu:'INR',tn:'TripRoam settlement'}).toString();
 const android=/Android/.test(navigator.userAgent),ios=/iPhone|iPad|iPod/.test(navigator.userAgent);
 async function report(){if(!valid||!checked)return;setBusy(true);setError('');try{const signature=String(amountPaise);if(submitted.current&&submitted.current!==signature)clientId.current=crypto.randomUUID();submitted.current=signature;await api('/payments/trips/'+data.trip._id+'/requests',{to:transaction.to,ledger,amountPaise,clientId:clientId.current});await onDone();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <dialog ref={dialog} className="payment-dialog" aria-labelledby="pay-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><div className="payment-heading"><h2 id="pay-title">Pay {name(transaction.to)}</h2><button className="icon-button" aria-label="Close payment" disabled={busy} onClick={onClose}><Icon name="close"/></button></div><p>{ledger==='kitty'?'Group Kitty':'Personal Pocket'} · Outstanding {money(transaction.amountPaise)}</p><label>Amount in rupees<input inputMode="decimal" value={amount} disabled={busy} onChange={e=>{setAmount(e.target.value);setChecked(false);}}/></label>
 {recipient?.upiId?<><p className="upi-address"><strong>{recipient.upiId}</strong><small>Added by this traveler · ownership not verified</small></p>{valid&&<div className="payment-buttons">{android?<><a className="primary" href={'upi://pay?'+query}>Choose UPI app</a><a className="secondary" href={'intent://pay?'+query+'#Intent;scheme=upi;package=com.google.android.apps.nbu.paisa.user;end'}>Google Pay</a><a className="secondary" href={'intent://pay?'+query+'#Intent;scheme=upi;package=com.phonepe.app;end'}>PhonePe</a><a className="secondary" href={'intent://pay?'+query+'#Intent;scheme=upi;package=net.one97.paytm;end'}>Paytm</a></>:ios?<a className="primary" href={'gpay://upi/pay?'+query}>Open Google Pay</a>:<p>Open your UPI app on your phone and use these payment details.</p>}</div>}<button className="text-button" onClick={async()=>{try{await navigator.clipboard.writeText(recipient.upiId);setError('UPI ID copied.');}catch{setError('Select the UPI ID above and copy it.');}}}>Copy UPI ID</button><p className="payment-note">Verify the recipient name and amount in your UPI app before entering your PIN. App links may be unavailable or blocked for personal payments; you can always pay manually.</p></>:<p>{recipient?'This person has not added a UPI ID. Ask them for payment details, or settle in cash.':'Loading payment details…'}</p>}
 <hr/><h3>Already paid?</h3><p>Paying does not update TripRoam automatically.</p><label className="receipt-check"><input type="checkbox" checked={checked} disabled={busy} onChange={e=>setChecked(e.target.checked)}/>I have paid this amount and want to request confirmation.</label><button className="primary" disabled={!valid||!checked||busy} onClick={report}>{busy?'Sending…':'I’ve paid · request approval'}</button>{!valid&&<p className="error">Enter an amount above zero, up to the outstanding balance.</p>}{error&&<p role="status">{error}</p>}</dialog>;
}
