import { Icon, money, isPrivate } from './ui.jsx';
export function activity(data){return [...data.expenses.map(e=>({...e,ledger:'personal'})),...data.purseEntries.map(e=>({...e,ledger:'purse'}))].sort((a,b)=>new Date(b.clientCreatedAt)-new Date(a.clientCreatedAt));}
function ActivityRow({entry,name,pending=false,state}){
  const confirmed=!pending||state==='synced';
  return <article className="activity-row"><span className={'activity-icon '+(entry.ledger==='purse'?'kitty-icon':'')}><Icon name={entry.ledger==='purse'?'purse':'expenses'}/></span><div className="activity-copy"><strong>{entry.title}</strong><small>{name(entry.recordedBy)} · {entry.ledger==='purse'?'Kitty':isPrivate(entry)?'Personal · Only you':'Personal · Shared'}</small><span className={'receipt-state '+(confirmed?'confirmed':'pending')}><Icon name={confirmed?'check':'clock'} size={14}/>{confirmed?'Synced':state==='failed'?'Needs attention':'Waiting to sync'} · {new Date(entry.clientCreatedAt).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'})}</span>{entry.splitAmong?.length>1&&<details><summary>View split</summary>{entry.splitAmong.map((id,index)=><small key={id}>{name(id)} · {money(Math.floor(entry.amountPaise/entry.splitAmong.length)+(index<entry.amountPaise%entry.splitAmong.length?1:0))}</small>)}</details>}</div><strong className="activity-amount">{money(entry.amountPaise)}</strong></article>;
}
export function Overview({data,userId,name,lead,manage,history,feed}){
  const spend=data.expenses.filter(e=>e.recordedBy===userId).reduce((s,e)=>s+e.amountPaise,0);
  const net=[...data.transactions,...(data.kittySettlement?.transactions||[])].reduce((s,t)=>s+(t.to===userId?t.amountPaise:0)-(t.from===userId?t.amountPaise:0),0);
  const recent=activity(data).slice(0,3);
  return <><section className="kitty-card"><div className="kitty-top"><span><Icon name="purse"/>Group kitty</span><span className="kitty-tag">Shared funds</span></div><h2>{money(data.trip.purseBalancePaise)}</h2><p>{data.trip.purseBalancePaise<0?'Advanced by the group lead':'Available in your shared Kitty'}</p><div className="kitty-actions"><button onClick={history}>View history<Icon name="arrow" size={16}/></button>{lead&&data.trip.status!=='ended'&&<button className="manage-kitty" onClick={manage}>Manage Kitty</button>}</div></section>
    <h2 className="section-title">Your balance</h2><div className="summary-grid"><section className="metric-card"><Icon name="expenses"/><span>Personal spend</span><strong>{money(spend)}</strong><small>Personal payments</small></section><section className={'metric-card '+(net<0?'negative':'positive')}><Icon name="balances"/><span>{data.kittySettlement?'Net balance':'Personal balance'}</span><strong>{money(Math.abs(net))}</strong><small>{net>0?'You are owed':net<0?'You owe':'All settled up'}</small></section></div>
    <div className="section-heading"><h2 className="section-title">Latest activity</h2><button className="text-button" onClick={feed}>See all<Icon name="arrow" size={16}/></button></div><section className="activity-list">{recent.length?recent.map(e=><ActivityRow key={e._id} entry={e} name={name}/>):<div className="friendly-empty"><Icon name="expenses"/><h3>A fresh start</h3><p>Your first expense will appear here.</p></div>}</section></>;
}
export function LiveFeed({data,rows,name,userId}){
  const saved=activity(data),ids=new Set(saved.map(e=>e.clientId));
  const items=[...saved.map(entry=>({entry})),...rows.filter(r=>!ids.has(r.entry.clientId)).map(r=>({...r,pending:true,entry:{...r.entry,recordedBy:userId}}))].sort((a,b)=>new Date(b.entry.clientCreatedAt)-new Date(a.entry.clientCreatedAt));
  return <><p className="page-description">Expenses and contributions, updated live.</p><section className="activity-list" aria-label="Trip activity">{items.length?items.map(row=><ActivityRow key={row.entry._id||row.entry.clientId} {...row} name={name}/>):<div className="friendly-empty"><Icon name="expenses"/><h3>No expenses yet</h3><p>Add an expense to get started.</p></div>}</section></>;
}
