const content = document.querySelector('#content');
const people = ['You', 'Aarav', 'Meera', 'Kabir'];
const entries = [
  { title: 'Dinner at the beach', amount: 320000, kind: 'kitty', time: '2026-11-12T20:30:00+05:30' },
  { title: 'Airport to our stay', amount: 160000, kind: 'kitty', time: '2026-11-12T15:15:00+05:30' },
  ...people.map(member => ({ title: `${member} added to the Kitty`, member, amount: 500000, kind: 'deposit', time: '2026-11-12T10:00:00+05:30' }))
];
let page = 'overview', kind = 'kitty';
const money = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(value / 100);
const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const total = type => entries.filter(e => e.kind === type).reduce((sum, e) => sum + e.amount, 0);
const title = (label, heading, desc, action = '') => `<p class="eyebrow">${label}</p><div class="heading"><div><h1>${heading}</h1><p class="muted">${desc}</p></div>${action}</div>`;
const button = (type, label) => `<button class="primary" data-add="${type}">＋ ${label}</button>`;
function rows(list) {
  if (!list.length) return '<p class="empty">No entries yet. Your next little adventure starts here.</p>';
  return [...list].sort((a,b) => b.time.localeCompare(a.time)).map(e => `<div class="row"><span class="icon">${e.kind === 'deposit' ? '↙' : e.kind === 'personal' ? '◈' : '↗'}</span><div class="row-body"><strong>${escape(e.title)}</strong><small>${e.kind === 'personal' ? 'Only visible to you' : e.kind === 'deposit' ? 'Kitty contribution' : 'Kitty · Split between 4'} · ${new Date(e.time).toLocaleTimeString('en-IN', {hour:'2-digit',minute:'2-digit'})}</small></div><div class="money">${e.kind === 'deposit' ? '+' : '−'}${money(e.amount)}<small>${e.pending ? 'Pending · preview' : 'Sample entry'}</small></div></div>`).join('');
}
function render() {
  const balance = total('deposit') - total('kitty');
  document.querySelectorAll('[data-page]').forEach(b => b.classList.toggle('selected', b.dataset.page === page));
  if (page === 'overview') content.innerHTML = title('GOOD TIMES. CLEAR ACCOUNTS.', 'Goa, with the gang', '12–16 November 2026 · 4 travelers · You’re the group lead', button('kitty','Add expense')) + `<section class="hero"><div><span class="badge">NEXT STOP: THE COAST</span><h2 style="margin-top:16px">Make memories.<br>We’ll keep the tabs.</h2><p>Your shared fund, little indulgences, and who owes what — all in one happy place.</p></div><div class="sun" aria-hidden="true">☀</div></section><section class="stats"><div class="card"><div class="label">Kitty balance</div><div class="amount">${money(balance)}</div><small>From ${money(total('deposit'))} deposited</small></div><div class="card"><div class="label">Group spending</div><div class="amount">${money(total('kitty'))}</div><small>Shared by 4 travelers</small></div><div class="card"><div class="label">Your pocket</div><div class="amount">${money(total('personal'))}</div><small>Just your personal spending</small></div></section><div class="columns"><section class="card"><div class="section-head"><h2>The trip, as it happens</h2><span class="badge">SAMPLE FEED</span></div>${rows(entries.filter(e=>e.kind !== 'personal'))}</section><section class="card"><h2>Your travel crew</h2><p class="muted">Good company. Shared adventures.</p>${people.map((p,i)=>`<div class="row"><span class="icon avatar">${p[0]}</span><div class="row-body"><strong>${p}</strong><small>${i===0?'Group lead':'Traveler'}</small></div><span class="badge">Joined</span></div>`).join('')}<small style="margin-top:24px">TRIP INVITE CODE · SAMPLE</small><div class="code">A9B2X7</div></section></div>`;
  if (page === 'kitty') content.innerHTML = title('THE SHARED FUND', 'Group Kitty', 'The group lead records deposits and shared spending.', button('kitty','Add expense')) + `<section class="hero"><div><h2>${money(balance)} available</h2><p>${money(total('deposit'))} contributed · ${money(total('kitty'))} spent</p></div>${button('deposit','Log deposit')}</section><section class="card" style="margin-top:24px"><h2>Kitty ledger</h2>${rows(entries.filter(e=>e.kind!=='personal'))}</section>`;
  if (page === 'personal') content.innerHTML = title('A LITTLE SOMETHING FOR YOU', 'Personal Pocket', 'Your private expenses stay out of group settlements.', button('personal','Add personal expense')) + `<section class="card"><h2>${money(total('personal'))} spent just on you</h2>${rows(entries.filter(e=>e.kind==='personal'))}</section>`;
  if (page === 'settlement') content.innerHTML = title('END ON A GOOD NOTE', 'Settle up', 'Preview of unused Kitty refunds. Final settlement logic arrives in Step 5.') + `<section class="card"><h2>Return the remaining Kitty</h2><p class="muted">Each traveler covers one quarter of shared expenses. Deposits minus that share determine refunds.</p>${people.map((p,i)=>{const share=Math.floor(total('kitty')/4)+(i<total('kitty')%4?1:0);const net=entries.filter(e=>e.kind==='deposit'&&e.member===p).reduce((s,e)=>s+e.amount,0)-share;return `<div class="row"><span class="icon avatar">${p[0]}</span><div class="row-body"><strong>${p}</strong><small>${net>=0?'Refund from Kitty':'Contribution still owed'}</small></div><strong>${money(Math.abs(net))}</strong></div>`}).join('')}</section><p class="muted">Person-to-person payment details will be implemented with the API. Personal Pocket expenses never enter this calculation.</p>`;
  if (page === 'join') content.innerHTML = title('EVERY TRIP STARTS HERE', 'Find your people', 'Start a shared travel fund or join the crew with a six-character code.') + `<div class="join-grid"><form id="create-form" class="card"><h2>Create a trip</h2><label>Trip name<input name="name" required maxlength="80" placeholder="e.g. Goa, with the gang"></label><button class="primary">Preview create</button><p class="muted">You become the group lead and receive an invite code.</p></form><form id="join-form" class="card"><h2>Join your crew</h2><label>Your name<input name="name" required maxlength="60" placeholder="What should we call you?"></label><label>Invite code<input name="code" required pattern="[A-Za-z0-9]{6}" maxlength="6" placeholder="A9B2X7" style="text-transform:uppercase"></label><button class="primary">Preview join</button></form></div>`;
}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.style.display='none',4500);}
document.addEventListener('click', e=>{
  const nav=e.target.closest('[data-page]');if(nav){page=nav.dataset.page;render();}
  const add=e.target.closest('[data-add]');if(add){kind=add.dataset.add;document.querySelector('#entry-form').reset();document.querySelector('#form-title').textContent=kind==='deposit'?'Log a Kitty deposit':kind==='personal'?'Add personal expense':'Add shared expense';document.querySelector('#member-label').style.display=kind==='deposit'?'grid':'none';document.querySelector('#split-note').textContent=kind==='kitty'?'Split equally between all four travelers.':kind==='personal'?'Private to you. Excluded from group settlement.':'Records a contribution; does not transfer money.';document.querySelector('#entry').showModal();}
});
document.querySelector('#close').onclick=()=>document.querySelector('#entry').close();
document.querySelector('#entry-form').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target);const amount=Math.round(Number(data.get('amount'))*100);if(!Number.isSafeInteger(amount)||amount<=0)return; if(kind==='kitty'&&amount>total('deposit')-total('kitty')){toast('This expense exceeds the available Kitty balance.');return;}entries.push({title:data.get('title'),amount,kind,member:data.get('member'),time:new Date().toISOString(),pending:document.querySelector('#offline').checked});document.querySelector('#entry').close();render();toast('Preview entry added. Refreshing resets sample data.');};
document.addEventListener('submit',e=>{if(['join-form','create-form'].includes(e.target.id)){e.preventDefault();toast('Flow preview complete. Accounts and trip creation arrive in Step 3.');}});
document.querySelector('#offline').onchange=e=>{document.querySelector('#network').hidden=!e.target.checked;};
render();
