const content = document.querySelector('#content');
const people = ['Shahrukh', 'Aarav', 'Meera', 'Kabir'];
const groupLeads = ['Shahrukh'];
const isLead = () => groupLeads.includes(current);
const purseOpening = 2000000; // Sample opening balance in paise.
const purseExpenses = [];
const purseBalance = () => purseOpening - purseExpenses.reduce((sum,e)=>sum+e.amount,0);
let current = 'Shahrukh', page = 'overview';
const entries = [
 {title:'Dinner at the beach',amount:320000,paidBy:'Shahrukh',splitAmong:[...people],time:'2026-09-14T20:30:00+05:30'},
 {title:'Coffee for you',amount:20000,paidBy:'Aarav',splitAmong:['Shahrukh'],time:'2026-09-14T16:00:00+05:30'},
 {title:'My souvenir',amount:45000,paidBy:'Shahrukh',splitAmong:['Shahrukh'],time:'2026-09-14T15:00:00+05:30'}
];
const money = value => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(value/100);
const escape = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const personal = e => e.splitAmong.length===1 && e.splitAmong[0]===e.paidBy;
const share = (e,p) => {const i=e.splitAmong.indexOf(p);return i<0?0:Math.floor(e.amount/e.splitAmong.length)+(i<e.amount%e.splitAmong.length?1:0);};
function balanceWith(friend){return entries.reduce((n,e)=>n+(e.paidBy===current?share(e,friend):0)-(e.paidBy===friend?share(e,current):0),0);}
const title = (heading,desc) => `<p class="eyebrow">GOA, WITH THE GANG · 4 TRAVELERS</p><div class="heading"><div><h1>${heading}</h1><p class="muted">${desc}</p></div><button class="primary" data-add>＋ Add expense</button></div>`;
function rows(list){return list.length?[...list].sort((a,b)=>new Date(b.time)-new Date(a.time)).map(e=>`<div class="row"><span class="icon">${personal(e)?'◈':'↗'}</span><div class="row-body"><strong>${escape(e.title)}</strong><small>${escape(e.paidBy)} paid · For ${e.splitAmong.map(escape).join(', ')}</small><small>${personal(e)?'Private · Only for yourself':e.paidBy===current?'You paid for '+(e.splitAmong.includes(current)?'yourself and friends':'friends'):e.splitAmong.includes(current)?'Your share: '+money(share(e,current)):'Shared expense'} · ${new Date(e.time).toLocaleDateString('en-IN')}${e.pending?' · Pending (preview)':''}</small></div><div class="money">${money(e.amount)}</div></div>`).join(''):'<p class="empty">Nothing here yet. Add what you paid for to get started.</p>';}
function debts(){return people.filter(p=>p!==current).map(p=>{const b=balanceWith(p);return `<div class="row"><span class="icon avatar">${p[0]}</span><div class="row-body"><strong>${escape(p)}</strong><small>${b>0?'Owes you':b<0?'You owe':'All square'}</small></div><strong>${money(Math.abs(b))}</strong></div>`}).join('');}
function render(){
 document.querySelector('#purse-nav').hidden=!isLead();
 if(page==='purse'&&!isLead())page='overview';
 document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('selected',b.dataset.page===page));
 const paid=entries.filter(e=>e.paidBy===current).reduce((s,e)=>s+e.amount,0);
 const owed=people.filter(p=>p!==current).reduce((s,p)=>s+Math.max(0,balanceWith(p)),0);
 const owe=people.filter(p=>p!==current).reduce((s,p)=>s+Math.max(0,-balanceWith(p)),0);
 const exampleFriend=people.find(p=>p!==current);
 if(page==='overview')content.innerHTML=title('You pay. We split.','Record what you paid from your own pocket. Choose who the expense was for.')+`${isLead()?`<section class="hero" style="margin-bottom:22px"><div><span class="badge">GROUP LEADS ONLY</span><h2>Group purse</h2><p>${money(purseBalance())} available · Shared trip money</p></div><button class="primary" data-page="purse">Open group purse →</button></section>`:''}<section class="stats"><div class="card"><div class="label">Paid by you</div><div class="amount">${money(paid)}</div><small>For yourself and friends</small></div><div class="card"><div class="label">Friends owe you</div><div class="amount">${money(owed)}</div><small>After balancing each friendship</small></div><div class="card"><div class="label">You owe friends</div><div class="amount">${money(owe)}</div><small>For things they paid for you</small></div></section><section class="how-it-works"><strong>One expense. Choose who it’s for.</strong><span>Paid ₹600 for ${exampleFriend}? Select <b>${exampleFriend} only</b>. He owes you ₹600.</span><span>Paid ₹600 for you and ${exampleFriend}? Select <b>both</b>. He owes you ₹300.</span><span>Bought something just for you? Select <b>yourself only</b>. No debt.</span></section><div class="columns"><section class="card"><h2>Trip activity</h2><p class="muted">Everyone records their own payments. Personal-only expenses stay private.</p>${rows(entries.filter(e=>!personal(e)))}</section><section class="card"><h2>Between you and friends</h2>${debts()}<button class="text-button" data-page="settlement">See payment breakdown →</button></section></div>`;
 if(page==='personal')content.innerHTML=title('Personal pocket','All expenses you recorded, whether for yourself, a friend, or the whole group.')+`<section class="card"><h2>${money(paid)} paid from your pocket</h2>${rows(entries.filter(e=>e.paidBy===current))}</section>`;
 if(page==='settlement')content.innerHTML=title('Who owes whom','Each friend’s balance includes payments in both directions.')+people.filter(p=>p!==current).map(p=>{const b=balanceWith(p),out=entries.filter(e=>e.paidBy===current).reduce((s,e)=>s+share(e,p),0),incoming=entries.filter(e=>e.paidBy===p).reduce((s,e)=>s+share(e,current),0);return `<section class="card" style="margin-bottom:16px"><h2>${escape(p)}</h2><div class="fund-equation"><span>You paid for ${escape(p)}<strong>${money(out)}</strong></span><span>${escape(p)} paid for you<strong>${money(incoming)}</strong></span></div><p><strong>${b>0?escape(p)+' owes you '+money(b):b<0?'You owe '+escape(p)+' '+money(-b):'All square'}</strong></p></section>`}).join('');
 if(page==='purse'&&isLead())content.innerHTML='<p class="eyebrow">GROUP LEADS ONLY</p><div class="heading"><div><h1>Group purse</h1><p class="muted">Shared trip money. Only group leads can view and spend from this purse.</p></div><button class="primary" data-purse-add>＋ Group expense</button></div>'+`<section class="hero"><div><small>AVAILABLE IN GROUP PURSE</small><div class="amount">${money(purseBalance())}</div><p>Sample opening balance: ${money(purseOpening)} · Spent: ${money(purseOpening-purseBalance())}</p></div></section><section class="card" style="margin-top:22px"><h2>Group purse expenses</h2>${purseExpenses.length?purseExpenses.map(e=>'<div class="row"><div class="row-body"><strong>'+escape(e.title)+'</strong><small>Recorded by '+escape(e.recordedBy)+(e.pending?' · Pending (preview)':'')+'</small></div><strong>'+money(e.amount)+'</strong></div>').join(''):'<p class="empty">No group expenses yet. Record a payment made from the shared purse.</p>'}</section><p class="muted">Personal-pocket payments and friend-to-friend balances are tracked separately.</p>`;
 if(page==='join')content.innerHTML=title('Bring your friends','Join the same trip. Each traveler records their own payments.')+`<section class="card"><h2>Trip invite code</h2><div class="code">A9B2X7</div><p class="muted">Sample code. Real trip creation and joining arrive with accounts.</p></section>`;
}
function selected(){return [...document.querySelectorAll('[name="beneficiary"]:checked')].map(e=>e.value);}
function updateImpact(){const splitAmong=selected(),amount=Math.round(Number(document.querySelector('[name="amount"]').value)*100)||0;const draft={amount,splitAmong};document.querySelector('#split-note').innerHTML=splitAmong.length?'<strong>'+ (splitAmong.length===1&&splitAmong[0]===current?'Just for you · No one owes anything':'Split equally between selected people')+'</strong>'+splitAmong.map(p=>'<small>'+escape(p)+(p===current?' · Your own share: ':' owes you: ')+money(share(draft,p))+'</small>').join(''):'<strong>Select at least one person.</strong>';}
function openEntry(){document.querySelector('#entry-form').reset();document.querySelector('#payer').textContent=current;document.querySelector('#beneficiaries').innerHTML=people.map(p=>`<label class="person-choice"><input type="checkbox" name="beneficiary" value="${p}" ${p===current?'checked':''}> ${p===current?'Myself ('+p+')':p}</label>`).join('');document.querySelector('#form-error').textContent='';updateImpact();document.querySelector('#entry').showModal();}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-page]');if(nav){page=nav.dataset.page;render();}if(e.target.closest('[data-add]'))openEntry();});
document.querySelector('#close').onclick=()=>document.querySelector('#entry').close();
document.querySelector('#entry-form').addEventListener('input',updateImpact);
document.querySelector('#entry-form').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target),amount=Math.round(Number(data.get('amount'))*100),splitAmong=selected(),description=String(data.get('title')).trim();if(!description||!splitAmong.length||!Number.isSafeInteger(amount)||amount<=0){document.querySelector('#form-error').textContent='Enter a description, a positive amount, and choose at least one person.';return;}entries.push({title:description,amount,paidBy:current,splitAmong,time:new Date().toISOString(),pending:document.querySelector('#offline').checked});document.querySelector('#entry').close();render();const toast=document.querySelector('#toast');toast.textContent='Expense recorded. Shares updated.';toast.style.display='block';setTimeout(()=>toast.style.display='none',3500);};
document.querySelector('#viewer').onchange=e=>{document.querySelector('#entry').close();document.querySelector('#purse-entry').close();current=e.target.value;render();};
document.querySelector('#offline').onchange=e=>document.querySelector('#network').hidden=!e.target.checked;
render();

function purseImpact(){const amount=Math.round(Number(document.querySelector('#purse-form [name="amount"]').value)*100)||0;document.querySelector('#purse-impact').textContent='Purse balance: '+money(purseBalance())+' → '+money(purseBalance()-amount);}
document.addEventListener('click',e=>{if(e.target.closest('[data-purse-add]')&&isLead()){document.querySelector('#purse-form').reset();document.querySelector('#purse-error').textContent='';purseImpact();document.querySelector('#purse-entry').showModal();}});
document.querySelector('#purse-close').onclick=()=>document.querySelector('#purse-entry').close();
document.querySelector('#purse-form').addEventListener('input',purseImpact);
document.querySelector('#purse-form').onsubmit=e=>{e.preventDefault();if(!isLead()){document.querySelector('#purse-entry').close();return;}const data=new FormData(e.target),amount=Math.round(Number(data.get('amount'))*100),description=String(data.get('title')).trim();if(!description||!Number.isSafeInteger(amount)||amount<=0||amount>purseBalance()){document.querySelector('#purse-error').textContent='Enter a description and an amount within the available purse balance.';return;}purseExpenses.unshift({title:description,amount,recordedBy:current,time:new Date().toISOString(),pending:document.querySelector('#offline').checked});document.querySelector('#purse-entry').close();render();};
